version: '3.3'
services:
  highscore:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: highscore:latest
    ports:
      - '8081:8081'
    depends_on:
      - "mongo"
    stdin_open: true
    tty: true
    volumes:
      - ./custom:/opt/custom
      - ./config/ban.json:/opt/config/ban.json
    environment:
      - HIGHSCORE_DB_URL=mongodb://mongo:27017/highscore
      - HIGHSCORE_TITLE=
      - HIGHSCORE_DESCRIPTION=
      - HIGHSCORE_LOGO_URL=
      - HIGHSCORE_FAVICON_URL=
      - HIGHSCORE_CSS_URL=

  mongo:
    image: mongo:5.0.8
    volumes:
      - data:/data/db

volumes:
  data:
